# Generated by Django 2.0.3 on 2018-03-21 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='target',
        ),
    ]
