# Generated by Django 2.0.3 on 2018-03-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_article_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='attach_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='attach_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
